### ISSUE TITLE
What should the namespace be?

### ISSUE THREAD

**Issue by jansensan** [jansensan/ng-useless#2]
Since using the `ng-`prefix may cause for a potential issue in the eventuality that AngularJS actually names a library the same, what should we use as a namespace?

Maybe we could use something like Code Against Humanity, with a nod to Cards Against Humanity? So that could give us a `cah-useless`namespace.

Other useless suggestions are welcome.

**Comment by mgnsharon** [comment]
I like that.  maybe even cah-tools or cah-toolbox.

**Comment by mgnsharon** [comment]
or possibly even ca-humanity

**Comment by jansensan** [comment]
Using only two letters like this could be confused with the [ISO 3166-1 alpha-2 standard for 2-letter country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

Let's go with `cah-tools`?

**Comment by jansensan** [comment]
Although I think `cah-useless` is more descriptive. Or `useless-cah`?

**Comment by mgnsharon** [comment]
i like cah-tools

**Comment by jansensan** [comment]
We need to set up a vote. We could also simply go for `code-against-humanity`.

**Comment by mgnsharon** [comment]
too long, although we could just make that be the project name, provided we don't get sued.

**Comment by jansensan** [comment]
This also means we have to figure out what license to use. Let's create a question for that.

**Comment by jansensan** [comment]
@csharon @brainsail: the project has been renamed `code-against-humanity`, please update your repository settings.
